### ISSUE TITLE
Problems following the installation steps

### ISSUE THREAD

**Issue by alexanderweber** [ashwanthkumar/marathon-alerts#13]
@air asked me to try out your tool. I had little problems following the README.md. It actually just concerns some of the paths, here is what worked out for me:

- `cd $GOPATH/src` instead of `cd $GOPATH`
- `mkdir -p github.com/ashwanthkumar/marathon-alerts` instead of `mkdir -p github.com/ashwanthkumar`
- `git clone https://github.com/ashwanthkumar/marathon-alerts.git github.com/ashwanthkumar/marathon-alerts` instead of `git clone https://github.com/ashwanthkumar/marathon-alerts.git github.com/ashwanthkumar`

I did commit these changes, but cannot push to a new branch as I am lacking the permissions.

**Comment by ashwanthkumar** [comment]
@alexanderweber Thanks for pointing out. I'm still learning to use proper dep management tool for Golang. You might want to fork this repo, push your changes onto a branch there and send the changes as PR. Would you like to do that or shall I take this change and commit this directly? 

Also did you know you can download the binaries directly from the [Releases](https://github.com/ashwanthkumar/marathon-alerts/releases)?

**Comment by alexanderweber** [comment]
@ashwanthkumar Thank you for pointing that out, I did create a PR.

Yeah, I did notice the releases, but also did want to try out the whole readme instructions.

**Comment by ashwanthkumar** [comment]
Thanks for that @alexanderweber. Please do share feedback / issues based on your usage.

**Comment by alexanderweber** [comment]
@ashwanthkumar I will!
