### ISSUE TITLE
Marathon GUI Deploy

### ISSUE THREAD

**Issue by utsysadmin** [ashwanthkumar/marathon-alerts#34]
Deploying through the GUI with the sample json.  I'm getting the following error:

cat: PID: No such file or directory
error: list of process IDs must follow -p

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
2016/12/20 15:46:30 App Checker Started.
2016/12/20 15:46:30 App Checker - Checking the status of all the apps every 30s
2016/12/20 15:46:30 Starting Alert Manager...
2016/12/20 15:46:30 Alert Manager Started.
I1220 15:46:30.513656 134863 health_checker.hpp:119] Ignoring failure as health check still in grace period
2016/12/20 15:47:00 Unexpected error - <nil>

**Comment by utsysadmin** [comment]
Current Marathon JSON:

{
  "id": "/tick/marathon-alerts",
  "cmd": "chmod +x marathon-alerts-linux-amd64 && ./marathon-alerts-linux-amd64 --uri ${MARATHON_URI} --slack-webhook ${SLACK_WEBHOOK} --pid PID",
  "cpus": 0.1,
  "mem": 64,
  "disk": 0,
  "instances": 0,
  "env": {
    "MARATHON_URI": "https://marathon...",
    "SLACK_WEBHOOK": "https://hooks.slack.com/..."
  },
  "healthChecks": [
    {
      "protocol": "COMMAND",
      "command": {
        "value": "ps -p $(cat PID)> /dev/null"
      },
      "gracePeriodSeconds": 2400,
      "intervalSeconds": 600,
      "timeoutSeconds": 200,
      "maxConsecutiveFailures": 3,
      "ignoreHttp1xx": false
    }
  ],
  "portDefinitions": [],
  "uris": [
    "https://github.com/ashwanthkumar/marathon-alerts/releases/download/v0.3.4/marathon-alerts-linux-amd64"
  ],
  "fetch": [
    {
      "uri": "https://github.com/ashwanthkumar/marathon-alerts/releases/download/v0.3.4/marathon-alerts-linux-amd64",
      "extract": false,
      "executable": false,
      "cache": false
    }
  ],
  "backoffFactor": 1.01,
  "maxLaunchDelaySeconds": 30,
  "upgradeStrategy": {
    "minimumHealthCapacity": 0.9,
    "maximumOverCapacity": 0.1
  }
}

**Comment by ashwanthkumar** [comment]
@utsysadmin Looks like the `PID` file is not getting generated. Can you please check the mesos sandbox directory and share if there's a file called `PID` ? 

Also can you please share the marathon version, you're using it to deploy.

**Comment by utsysadmin** [comment]
The PID file is there and contains a valid PID number... I'm wondering if it's not there right away when the health check runs.  I am running Marathon 1.3.3.

**Comment by ashwanthkumar** [comment]
@utsysadmin That's right it wouldn't be there right away - That's why the `maxConsecutiveFailures` should help. Does it fail all the 3 times with healthcheck failure and does marathon try to re-deploy the app over and over again?

**Comment by utsysadmin** [comment]
It never retries.  Marathon appears to kill it after the "unexpected error -" and then re-deploys it over and over again.

**Comment by ashwanthkumar** [comment]
Ah - I somehow missed the last log line 
```
2016/12/20 15:47:00 Unexpected error -
```

Is there anything after this line? It seems to come from [this line](https://github.com/ashwanthkumar/marathon-alerts/blob/69ffdc30f894085045dd4dd2e8c6ed1a5e3cfa13/app-checker.go#L63). This is the marathon-alerts failing fast dumping the error. I haven't tried with Marathon 1.x before, may be the APIs have changed and my client is not able to access it. Next steps,
1. I'll check for Marathon 1.x compatibility and get back to you in a couple of days
2. Can you please check and let me know if you've any more errors after the above log snippet?

**Comment by utsysadmin** [comment]
Unfortunately there isn't any log information after that.  I'm thinking we are using URI/v2 instead of the old URI/v1.  Also, I have a reverse proxy that eliminates the need for a port number on my URI.  IE https://marathon.domain.com instead of https://server.domain.com:8443.  I tried both ways for the URI and had the same result.

**Comment by ashwanthkumar** [comment]
The underlying marathon-client also uses `/v2` AFAIK - we're running 0.10 in production for more than a year and that also uses `/v2`. 

Anyways, thanks for the pointers and feedback. Let me work on improving the logging and Marathon1.x compatibility. 

Are you familiar with Go language and would like to take a stab at this issue?

**Comment by ashwanthkumar** [comment]
We recently migrated our marathon to 1.x and marathon-alerts was working out of the box with no errors. I'm closing this issue for now.
